FROM tensorflow/tensorflow:latest-gpu-py3

# Adds metadata to the image as a key value pair example LABEL version="1.0"
#LABEL maintainer="Virginia Negri <virginia.negri20@gmail.com>"

RUN pip install tqdm numpy pandas pillow

#COPY ./run.py /run.py
#COPY ./../static/hotel_info /data

#CMD ["python3”, "./hotel/run.py"]

